# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:

- job: Linux
  
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    maxParallel: 2
    matrix:
      debug:
        _configuration: Debug
      release:
        _configuration: Release
  timeoutInMinutes: 10

  steps:
  - script: echo Linux $(_configuration) Hello, world!
    displayName: 'Linux $(_configuration) Run a one-line script'

  - script: |
      echo Linux Add other tasks to build, test, and deploy your project.
      echo Linux See https://aka.ms/yaml
    displayName: 'Linux Run a multi-line script'


#- job: macOS
#  
#  pool:
#    vmImage: 'macOS-10.13'
#
#  steps:
#  - script: echo macOS Hello, world from!
#    displayName: 'macOS Run a one-line script'
#
#  - script: |
#      echo macOS Add other tasks to build, test, and deploy your project.
#      echo macOS See https://aka.ms/yaml
#    displayName: 'macOS Run a multi-line script update'


- job: Windows
  
  pool:
    vmImage: 'windows-2019'

  steps:
  - script: echo Windows Hello, world from!
    displayName: 'Windows Run a one-line script'

  - script: |
      echo Windows Add other tasks to build, test, and deploy your project.
      echo Windows See https://aka.ms/yaml
    displayName: 'Windows Run a multi-line script'
